# Generated by Django 5.0.3 on 2024-05-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCSApp', '0002_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='cleared',
        ),
        migrations.AddField(
            model_name='clearance',
            name='cleared',
            field=models.BooleanField(default=1, verbose_name=True),
            preserve_default=False,
        ),
    ]
